### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by FuriousOatmeal** [nerdhaus/eldrich#33]
I'm getting an "Access Denied" page whenever I navigate from "My Account" page to any of the links under "Add Your Own". This just started today, I was able to access the pages from a couple of days ago.

**Comment by eaton** [comment]
Well, *that's* no good! There was a brief hiccup with access to the "Add a new item" form a couple of days ago, but it's since been resolved. Are you still seeing it?

I just logged on using a 'GM' account and access to them seems to be working again…

**Comment by FuriousOatmeal** [comment]
Yeah it was fixed by the next day.

**Comment by eaton** [comment]
Thanks!

I'll be sure to triple-test some of those upcoming changes now that People Other Than Me™ are actually using the site…

**Comment by ghost** [comment]
I'm actually seeing this now. In the Rogues Gallery, I see my account with no role, though I've been using the site to manage my GM content.

**Comment by eaton** [comment]
Just took a look at it, and somehow the 'GM' flag got removed — I'm looking closer to make sure nothing goofier rippled out from that, but I've re'upped your GM permissions so everything should be working.

**Comment by ghost** [comment]
It's working again! You're the best.
